#If (recorderActive && recorderKbMouseEnabled)
~*LButton::
    RecorderAddEvent("mousebtn", "LButton", "Down")
return

~*LButton Up::
    RecorderAddEvent("mousebtn", "LButton", "Up")
return

~*RButton::
    RecorderAddEvent("mousebtn", "RButton", "Down")
return

~*RButton Up::
    RecorderAddEvent("mousebtn", "RButton", "Up")
return

~*MButton::
    RecorderAddEvent("mousebtn", "MButton", "Down")
return

~*MButton Up::
    RecorderAddEvent("mousebtn", "MButton", "Up")
return

~*XButton1::
    RecorderAddEvent("mousebtn", "XButton1", "Down")
return

~*XButton1 Up::
    RecorderAddEvent("mousebtn", "XButton1", "Up")
return

~*XButton2::
    RecorderAddEvent("mousebtn", "XButton2", "Down")
return

~*XButton2 Up::
    RecorderAddEvent("mousebtn", "XButton2", "Up")
return

~*WheelUp::
    RecorderAddEvent("mousebtn", "WheelUp", "")
return

~*WheelDown::
    RecorderAddEvent("mousebtn", "WheelDown", "")
return

~*WheelLeft::
    RecorderAddEvent("mousebtn", "WheelLeft", "")
return

~*WheelRight::
    RecorderAddEvent("mousebtn", "WheelRight", "")
return

~*a::RecorderAddEvent("key", "a", "Down")
~*a up::RecorderAddEvent("key", "a", "Up")
~*b::RecorderAddEvent("key", "b", "Down")
~*b up::RecorderAddEvent("key", "b", "Up")
~*c::RecorderAddEvent("key", "c", "Down")
~*c up::RecorderAddEvent("key", "c", "Up")
~*d::RecorderAddEvent("key", "d", "Down")
~*d up::RecorderAddEvent("key", "d", "Up")
~*e::RecorderAddEvent("key", "e", "Down")
~*e up::RecorderAddEvent("key", "e", "Up")
~*f::RecorderAddEvent("key", "f", "Down")
~*f up::RecorderAddEvent("key", "f", "Up")
~*g::RecorderAddEvent("key", "g", "Down")
~*g up::RecorderAddEvent("key", "g", "Up")
~*h::RecorderAddEvent("key", "h", "Down")
~*h up::RecorderAddEvent("key", "h", "Up")
~*i::RecorderAddEvent("key", "i", "Down")
~*i up::RecorderAddEvent("key", "i", "Up")
~*j::RecorderAddEvent("key", "j", "Down")
~*j up::RecorderAddEvent("key", "j", "Up")
~*k::RecorderAddEvent("key", "k", "Down")
~*k up::RecorderAddEvent("key", "k", "Up")
~*l::RecorderAddEvent("key", "l", "Down")
~*l up::RecorderAddEvent("key", "l", "Up")
~*m::RecorderAddEvent("key", "m", "Down")
~*m up::RecorderAddEvent("key", "m", "Up")
~*n::RecorderAddEvent("key", "n", "Down")
~*n up::RecorderAddEvent("key", "n", "Up")
~*o::RecorderAddEvent("key", "o", "Down")
~*o up::RecorderAddEvent("key", "o", "Up")
~*p::RecorderAddEvent("key", "p", "Down")
~*p up::RecorderAddEvent("key", "p", "Up")
~*q::RecorderAddEvent("key", "q", "Down")
~*q up::RecorderAddEvent("key", "q", "Up")
~*r::RecorderAddEvent("key", "r", "Down")
~*r up::RecorderAddEvent("key", "r", "Up")
~*s::RecorderAddEvent("key", "s", "Down")
~*s up::RecorderAddEvent("key", "s", "Up")
~*t::RecorderAddEvent("key", "t", "Down")
~*t up::RecorderAddEvent("key", "t", "Up")
~*u::RecorderAddEvent("key", "u", "Down")
~*u up::RecorderAddEvent("key", "u", "Up")
~*v::RecorderAddEvent("key", "v", "Down")
~*v up::RecorderAddEvent("key", "v", "Up")
~*w::RecorderAddEvent("key", "w", "Down")
~*w up::RecorderAddEvent("key", "w", "Up")
~*x::RecorderAddEvent("key", "x", "Down")
~*x up::RecorderAddEvent("key", "x", "Up")
~*y::RecorderAddEvent("key", "y", "Down")
~*y up::RecorderAddEvent("key", "y", "Up")
~*z::RecorderAddEvent("key", "z", "Down")
~*z up::RecorderAddEvent("key", "z", "Up")
~*1::RecorderAddEvent("key", "1", "Down")
~*1 up::RecorderAddEvent("key", "1", "Up")
~*2::RecorderAddEvent("key", "2", "Down")
~*2 up::RecorderAddEvent("key", "2", "Up")
~*3::RecorderAddEvent("key", "3", "Down")
~*3 up::RecorderAddEvent("key", "3", "Up")
~*4::RecorderAddEvent("key", "4", "Down")
~*4 up::RecorderAddEvent("key", "4", "Up")
~*5::RecorderAddEvent("key", "5", "Down")
~*5 up::RecorderAddEvent("key", "5", "Up")
~*6::RecorderAddEvent("key", "6", "Down")
~*6 up::RecorderAddEvent("key", "6", "Up")
~*7::RecorderAddEvent("key", "7", "Down")
~*7 up::RecorderAddEvent("key", "7", "Up")
~*8::RecorderAddEvent("key", "8", "Down")
~*8 up::RecorderAddEvent("key", "8", "Up")
~*9::RecorderAddEvent("key", "9", "Down")
~*9 up::RecorderAddEvent("key", "9", "Up")
~*0::RecorderAddEvent("key", "0", "Down")
~*0 up::RecorderAddEvent("key", "0", "Up")
~*vkBC::RecorderAddEvent("key", "vkBC", "Down")
~*vkBC up::RecorderAddEvent("key", "vkBC", "Up")
~*vkBE::RecorderAddEvent("key", "vkBE", "Down")
~*vkBE up::RecorderAddEvent("key", "vkBE", "Up")
~*vkBF::RecorderAddEvent("key", "vkBF", "Down")
~*vkBF up::RecorderAddEvent("key", "vkBF", "Up")
~*vkBA::RecorderAddEvent("key", "vkBA", "Down")
~*vkBA up::RecorderAddEvent("key", "vkBA", "Up")
~*vkDE::RecorderAddEvent("key", "vkDE", "Down")
~*vkDE up::RecorderAddEvent("key", "vkDE", "Up")
~*vkDB::RecorderAddEvent("key", "vkDB", "Down")
~*vkDB up::RecorderAddEvent("key", "vkDB", "Up")
~*vkDD::RecorderAddEvent("key", "vkDD", "Down")
~*vkDD up::RecorderAddEvent("key", "vkDD", "Up")
~*vkDC::RecorderAddEvent("key", "vkDC", "Down")
~*vkDC up::RecorderAddEvent("key", "vkDC", "Up")
~*vkBD::RecorderAddEvent("key", "vkBD", "Down")
~*vkBD up::RecorderAddEvent("key", "vkBD", "Up")
~*vkBB::RecorderAddEvent("key", "vkBB", "Down")
~*vkBB up::RecorderAddEvent("key", "vkBB", "Up")
~*vkC0::RecorderAddEvent("key", "vkC0", "Down")
~*vkC0 up::RecorderAddEvent("key", "vkC0", "Up")
~*Space::RecorderAddEvent("key", "Space", "Down")
~*Space up::RecorderAddEvent("key", "Space", "Up")
~*Enter::RecorderAddEvent("key", "Enter", "Down")
~*Enter up::RecorderAddEvent("key", "Enter", "Up")
~*Tab::RecorderAddEvent("key", "Tab", "Down")
~*Tab up::RecorderAddEvent("key", "Tab", "Up")
~*Backspace::RecorderAddEvent("key", "Backspace", "Down")
~*Backspace up::RecorderAddEvent("key", "Backspace", "Up")
~*Esc::RecorderAddEvent("key", "Esc", "Down")
~*Esc up::RecorderAddEvent("key", "Esc", "Up")
~*Shift::RecorderAddEvent("key", "Shift", "Down")
~*Shift up::RecorderAddEvent("key", "Shift", "Up")
~*Ctrl::RecorderAddEvent("key", "Ctrl", "Down")
~*Ctrl up::RecorderAddEvent("key", "Ctrl", "Up")
~*Alt::RecorderAddEvent("key", "Alt", "Down")
~*Alt up::RecorderAddEvent("key", "Alt", "Up")
~*LShift::RecorderAddEvent("key", "LShift", "Down")
~*LShift up::RecorderAddEvent("key", "LShift", "Up")
~*RShift::RecorderAddEvent("key", "RShift", "Down")
~*RShift up::RecorderAddEvent("key", "RShift", "Up")
~*LControl::RecorderAddEvent("key", "LControl", "Down")
~*LControl up::RecorderAddEvent("key", "LControl", "Up")
~*RControl::RecorderAddEvent("key", "RControl", "Down")
~*RControl up::RecorderAddEvent("key", "RControl", "Up")
~*LAlt::RecorderAddEvent("key", "LAlt", "Down")
~*LAlt up::RecorderAddEvent("key", "LAlt", "Up")
~*RAlt::RecorderAddEvent("key", "RAlt", "Down")
~*RAlt up::RecorderAddEvent("key", "RAlt", "Up")
~*Home::RecorderAddEvent("key", "Home", "Down")
~*Home up::RecorderAddEvent("key", "Home", "Up")
~*End::RecorderAddEvent("key", "End", "Down")
~*End up::RecorderAddEvent("key", "End", "Up")
~*PgUp::RecorderAddEvent("key", "PgUp", "Down")
~*PgUp up::RecorderAddEvent("key", "PgUp", "Up")
~*PgDn::RecorderAddEvent("key", "PgDn", "Down")
~*PgDn up::RecorderAddEvent("key", "PgDn", "Up")
~*Insert::RecorderAddEvent("key", "Insert", "Down")
~*Insert up::RecorderAddEvent("key", "Insert", "Up")
~*Delete::RecorderAddEvent("key", "Delete", "Down")
~*Delete up::RecorderAddEvent("key", "Delete", "Up")
~*Up::RecorderAddEvent("key", "Up", "Down")
~*Up up::RecorderAddEvent("key", "Up", "Up")
~*Down::RecorderAddEvent("key", "Down", "Down")
~*Down up::RecorderAddEvent("key", "Down", "Up")
~*Left::RecorderAddEvent("key", "Left", "Down")
~*Left up::RecorderAddEvent("key", "Left", "Up")
~*Right::RecorderAddEvent("key", "Right", "Down")
~*Right up::RecorderAddEvent("key", "Right", "Up")
~*Numpad0::RecorderAddEvent("key", "Numpad0", "Down")
~*Numpad0 up::RecorderAddEvent("key", "Numpad0", "Up")
~*Numpad1::RecorderAddEvent("key", "Numpad1", "Down")
~*Numpad1 up::RecorderAddEvent("key", "Numpad1", "Up")
~*Numpad2::RecorderAddEvent("key", "Numpad2", "Down")
~*Numpad2 up::RecorderAddEvent("key", "Numpad2", "Up")
~*Numpad3::RecorderAddEvent("key", "Numpad3", "Down")
~*Numpad3 up::RecorderAddEvent("key", "Numpad3", "Up")
~*Numpad4::RecorderAddEvent("key", "Numpad4", "Down")
~*Numpad4 up::RecorderAddEvent("key", "Numpad4", "Up")
~*Numpad5::RecorderAddEvent("key", "Numpad5", "Down")
~*Numpad5 up::RecorderAddEvent("key", "Numpad5", "Up")
~*Numpad6::RecorderAddEvent("key", "Numpad6", "Down")
~*Numpad6 up::RecorderAddEvent("key", "Numpad6", "Up")
~*Numpad7::RecorderAddEvent("key", "Numpad7", "Down")
~*Numpad7 up::RecorderAddEvent("key", "Numpad7", "Up")
~*Numpad8::RecorderAddEvent("key", "Numpad8", "Down")
~*Numpad8 up::RecorderAddEvent("key", "Numpad8", "Up")
~*Numpad9::RecorderAddEvent("key", "Numpad9", "Down")
~*Numpad9 up::RecorderAddEvent("key", "Numpad9", "Up")
~*NumpadDot::RecorderAddEvent("key", "NumpadDot", "Down")
~*NumpadDot up::RecorderAddEvent("key", "NumpadDot", "Up")
~*NumpadDiv::RecorderAddEvent("key", "NumpadDiv", "Down")
~*NumpadDiv up::RecorderAddEvent("key", "NumpadDiv", "Up")
~*NumpadMult::RecorderAddEvent("key", "NumpadMult", "Down")
~*NumpadMult up::RecorderAddEvent("key", "NumpadMult", "Up")
~*NumpadAdd::RecorderAddEvent("key", "NumpadAdd", "Down")
~*NumpadAdd up::RecorderAddEvent("key", "NumpadAdd", "Up")
~*NumpadSub::RecorderAddEvent("key", "NumpadSub", "Down")
~*NumpadSub up::RecorderAddEvent("key", "NumpadSub", "Up")
~*NumpadEnter::RecorderAddEvent("key", "NumpadEnter", "Down")
~*NumpadEnter up::RecorderAddEvent("key", "NumpadEnter", "Up")
~*F1::RecorderAddEvent("key", "F1", "Down")
~*F1 up::RecorderAddEvent("key", "F1", "Up")
~*F2::RecorderAddEvent("key", "F2", "Down")
~*F2 up::RecorderAddEvent("key", "F2", "Up")
~*F3::RecorderAddEvent("key", "F3", "Down")
~*F3 up::RecorderAddEvent("key", "F3", "Up")
~*F4::RecorderAddEvent("key", "F4", "Down")
~*F4 up::RecorderAddEvent("key", "F4", "Up")
~*F5::RecorderAddEvent("key", "F5", "Down")
~*F5 up::RecorderAddEvent("key", "F5", "Up")
~*F6::RecorderAddEvent("key", "F6", "Down")
~*F6 up::RecorderAddEvent("key", "F6", "Up")
~*F7::RecorderAddEvent("key", "F7", "Down")
~*F7 up::RecorderAddEvent("key", "F7", "Up")
~*F8::RecorderAddEvent("key", "F8", "Down")
~*F8 up::RecorderAddEvent("key", "F8", "Up")
~*F9::RecorderAddEvent("key", "F9", "Down")
~*F9 up::RecorderAddEvent("key", "F9", "Up")
~*F10::RecorderAddEvent("key", "F10", "Down")
~*F10 up::RecorderAddEvent("key", "F10", "Up")
~*F11::RecorderAddEvent("key", "F11", "Down")
~*F11 up::RecorderAddEvent("key", "F11", "Up")
~*F12::RecorderAddEvent("key", "F12", "Down")
~*F12 up::RecorderAddEvent("key", "F12", "Up")
#If
