; Keyboard and mouse-button recorder hooks for Macros_v2.ahk.
; Keep this include after the main startup block; hotkeys end AutoHotkey's
; auto-execute section.

#HotIf RecorderKeysActive()
~*LButton::RecorderKeys_RecordMouseButton("LButton", "Down")
~*LButton Up::RecorderKeys_RecordMouseButton("LButton", "Up")
~*RButton::RecorderKeys_RecordMouseButton("RButton", "Down")
~*RButton Up::RecorderKeys_RecordMouseButton("RButton", "Up")
~*MButton::RecorderKeys_RecordMouseButton("MButton", "Down")
~*MButton Up::RecorderKeys_RecordMouseButton("MButton", "Up")
~*XButton1::RecorderKeys_RecordMouseButton("XButton1", "Down")
~*XButton1 Up::RecorderKeys_RecordMouseButton("XButton1", "Up")
~*XButton2::RecorderKeys_RecordMouseButton("XButton2", "Down")
~*XButton2 Up::RecorderKeys_RecordMouseButton("XButton2", "Up")
~*WheelUp::RecorderKeys_RecordMouseButton("WheelUp", "")
~*WheelDown::RecorderKeys_RecordMouseButton("WheelDown", "")
~*WheelLeft::RecorderKeys_RecordMouseButton("WheelLeft", "")
~*WheelRight::RecorderKeys_RecordMouseButton("WheelRight", "")

~*a::RecorderKeys_RecordKey("a", "Down")
~*a Up::RecorderKeys_RecordKey("a", "Up")
~*b::RecorderKeys_RecordKey("b", "Down")
~*b Up::RecorderKeys_RecordKey("b", "Up")
~*c::RecorderKeys_RecordKey("c", "Down")
~*c Up::RecorderKeys_RecordKey("c", "Up")
~*d::RecorderKeys_RecordKey("d", "Down")
~*d Up::RecorderKeys_RecordKey("d", "Up")
~*e::RecorderKeys_RecordKey("e", "Down")
~*e Up::RecorderKeys_RecordKey("e", "Up")
~*f::RecorderKeys_RecordKey("f", "Down")
~*f Up::RecorderKeys_RecordKey("f", "Up")
~*g::RecorderKeys_RecordKey("g", "Down")
~*g Up::RecorderKeys_RecordKey("g", "Up")
~*h::RecorderKeys_RecordKey("h", "Down")
~*h Up::RecorderKeys_RecordKey("h", "Up")
~*i::RecorderKeys_RecordKey("i", "Down")
~*i Up::RecorderKeys_RecordKey("i", "Up")
~*j::RecorderKeys_RecordKey("j", "Down")
~*j Up::RecorderKeys_RecordKey("j", "Up")
~*k::RecorderKeys_RecordKey("k", "Down")
~*k Up::RecorderKeys_RecordKey("k", "Up")
~*l::RecorderKeys_RecordKey("l", "Down")
~*l Up::RecorderKeys_RecordKey("l", "Up")
~*m::RecorderKeys_RecordKey("m", "Down")
~*m Up::RecorderKeys_RecordKey("m", "Up")
~*n::RecorderKeys_RecordKey("n", "Down")
~*n Up::RecorderKeys_RecordKey("n", "Up")
~*o::RecorderKeys_RecordKey("o", "Down")
~*o Up::RecorderKeys_RecordKey("o", "Up")
~*p::RecorderKeys_RecordKey("p", "Down")
~*p Up::RecorderKeys_RecordKey("p", "Up")
~*q::RecorderKeys_RecordKey("q", "Down")
~*q Up::RecorderKeys_RecordKey("q", "Up")
~*r::RecorderKeys_RecordKey("r", "Down")
~*r Up::RecorderKeys_RecordKey("r", "Up")
~*s::RecorderKeys_RecordKey("s", "Down")
~*s Up::RecorderKeys_RecordKey("s", "Up")
~*t::RecorderKeys_RecordKey("t", "Down")
~*t Up::RecorderKeys_RecordKey("t", "Up")
~*u::RecorderKeys_RecordKey("u", "Down")
~*u Up::RecorderKeys_RecordKey("u", "Up")
~*v::RecorderKeys_RecordKey("v", "Down")
~*v Up::RecorderKeys_RecordKey("v", "Up")
~*w::RecorderKeys_RecordKey("w", "Down")
~*w Up::RecorderKeys_RecordKey("w", "Up")
~*x::RecorderKeys_RecordKey("x", "Down")
~*x Up::RecorderKeys_RecordKey("x", "Up")
~*y::RecorderKeys_RecordKey("y", "Down")
~*y Up::RecorderKeys_RecordKey("y", "Up")
~*z::RecorderKeys_RecordKey("z", "Down")
~*z Up::RecorderKeys_RecordKey("z", "Up")

~*1::RecorderKeys_RecordKey("1", "Down")
~*1 Up::RecorderKeys_RecordKey("1", "Up")
~*2::RecorderKeys_RecordKey("2", "Down")
~*2 Up::RecorderKeys_RecordKey("2", "Up")
~*3::RecorderKeys_RecordKey("3", "Down")
~*3 Up::RecorderKeys_RecordKey("3", "Up")
~*4::RecorderKeys_RecordKey("4", "Down")
~*4 Up::RecorderKeys_RecordKey("4", "Up")
~*5::RecorderKeys_RecordKey("5", "Down")
~*5 Up::RecorderKeys_RecordKey("5", "Up")
~*6::RecorderKeys_RecordKey("6", "Down")
~*6 Up::RecorderKeys_RecordKey("6", "Up")
~*7::RecorderKeys_RecordKey("7", "Down")
~*7 Up::RecorderKeys_RecordKey("7", "Up")
~*8::RecorderKeys_RecordKey("8", "Down")
~*8 Up::RecorderKeys_RecordKey("8", "Up")
~*9::RecorderKeys_RecordKey("9", "Down")
~*9 Up::RecorderKeys_RecordKey("9", "Up")
~*0::RecorderKeys_RecordKey("0", "Down")
~*0 Up::RecorderKeys_RecordKey("0", "Up")

~*vkBC::RecorderKeys_RecordKey("vkBC", "Down")
~*vkBC Up::RecorderKeys_RecordKey("vkBC", "Up")
~*vkBE::RecorderKeys_RecordKey("vkBE", "Down")
~*vkBE Up::RecorderKeys_RecordKey("vkBE", "Up")
~*vkBF::RecorderKeys_RecordKey("vkBF", "Down")
~*vkBF Up::RecorderKeys_RecordKey("vkBF", "Up")
~*vkBA::RecorderKeys_RecordKey("vkBA", "Down")
~*vkBA Up::RecorderKeys_RecordKey("vkBA", "Up")
~*vkDE::RecorderKeys_RecordKey("vkDE", "Down")
~*vkDE Up::RecorderKeys_RecordKey("vkDE", "Up")
~*vkDB::RecorderKeys_RecordKey("vkDB", "Down")
~*vkDB Up::RecorderKeys_RecordKey("vkDB", "Up")
~*vkDD::RecorderKeys_RecordKey("vkDD", "Down")
~*vkDD Up::RecorderKeys_RecordKey("vkDD", "Up")
~*vkDC::RecorderKeys_RecordKey("vkDC", "Down")
~*vkDC Up::RecorderKeys_RecordKey("vkDC", "Up")
~*vkBD::RecorderKeys_RecordKey("vkBD", "Down")
~*vkBD Up::RecorderKeys_RecordKey("vkBD", "Up")
~*vkBB::RecorderKeys_RecordKey("vkBB", "Down")
~*vkBB Up::RecorderKeys_RecordKey("vkBB", "Up")
~*vkC0::RecorderKeys_RecordKey("vkC0", "Down")
~*vkC0 Up::RecorderKeys_RecordKey("vkC0", "Up")

~*Space::RecorderKeys_RecordKey("Space", "Down")
~*Space Up::RecorderKeys_RecordKey("Space", "Up")
~*Enter::RecorderKeys_RecordKey("Enter", "Down")
~*Enter Up::RecorderKeys_RecordKey("Enter", "Up")
~*Tab::RecorderKeys_RecordKey("Tab", "Down")
~*Tab Up::RecorderKeys_RecordKey("Tab", "Up")
~*Backspace::RecorderKeys_RecordKey("Backspace", "Down")
~*Backspace Up::RecorderKeys_RecordKey("Backspace", "Up")
~*LShift::RecorderKeys_RecordKey("LShift", "Down")
~*LShift Up::RecorderKeys_RecordKey("LShift", "Up")
~*RShift::RecorderKeys_RecordKey("RShift", "Down")
~*RShift Up::RecorderKeys_RecordKey("RShift", "Up")
~*LControl::RecorderKeys_RecordKey("LControl", "Down")
~*LControl Up::RecorderKeys_RecordKey("LControl", "Up")
~*RControl::RecorderKeys_RecordKey("RControl", "Down")
~*RControl Up::RecorderKeys_RecordKey("RControl", "Up")
~*LAlt::RecorderKeys_RecordKey("LAlt", "Down")
~*LAlt Up::RecorderKeys_RecordKey("LAlt", "Up")
~*RAlt::RecorderKeys_RecordKey("RAlt", "Down")
~*RAlt Up::RecorderKeys_RecordKey("RAlt", "Up")

~*Home::RecorderKeys_RecordKey("Home", "Down")
~*Home Up::RecorderKeys_RecordKey("Home", "Up")
~*End::RecorderKeys_RecordKey("End", "Down")
~*End Up::RecorderKeys_RecordKey("End", "Up")
~*PgUp::RecorderKeys_RecordKey("PgUp", "Down")
~*PgUp Up::RecorderKeys_RecordKey("PgUp", "Up")
~*PgDn::RecorderKeys_RecordKey("PgDn", "Down")
~*PgDn Up::RecorderKeys_RecordKey("PgDn", "Up")
~*Insert::RecorderKeys_RecordKey("Insert", "Down")
~*Insert Up::RecorderKeys_RecordKey("Insert", "Up")
~*Delete::RecorderKeys_RecordKey("Delete", "Down")
~*Delete Up::RecorderKeys_RecordKey("Delete", "Up")
~*Up::RecorderKeys_RecordKey("Up", "Down")
~*Up Up::RecorderKeys_RecordKey("Up", "Up")
~*Down::RecorderKeys_RecordKey("Down", "Down")
~*Down Up::RecorderKeys_RecordKey("Down", "Up")
~*Left::RecorderKeys_RecordKey("Left", "Down")
~*Left Up::RecorderKeys_RecordKey("Left", "Up")
~*Right::RecorderKeys_RecordKey("Right", "Down")
~*Right Up::RecorderKeys_RecordKey("Right", "Up")

~*Numpad0::RecorderKeys_RecordKey("Numpad0", "Down")
~*Numpad0 Up::RecorderKeys_RecordKey("Numpad0", "Up")
~*Numpad1::RecorderKeys_RecordKey("Numpad1", "Down")
~*Numpad1 Up::RecorderKeys_RecordKey("Numpad1", "Up")
~*Numpad2::RecorderKeys_RecordKey("Numpad2", "Down")
~*Numpad2 Up::RecorderKeys_RecordKey("Numpad2", "Up")
~*Numpad3::RecorderKeys_RecordKey("Numpad3", "Down")
~*Numpad3 Up::RecorderKeys_RecordKey("Numpad3", "Up")
~*Numpad4::RecorderKeys_RecordKey("Numpad4", "Down")
~*Numpad4 Up::RecorderKeys_RecordKey("Numpad4", "Up")
~*Numpad5::RecorderKeys_RecordKey("Numpad5", "Down")
~*Numpad5 Up::RecorderKeys_RecordKey("Numpad5", "Up")
~*Numpad6::RecorderKeys_RecordKey("Numpad6", "Down")
~*Numpad6 Up::RecorderKeys_RecordKey("Numpad6", "Up")
~*Numpad7::RecorderKeys_RecordKey("Numpad7", "Down")
~*Numpad7 Up::RecorderKeys_RecordKey("Numpad7", "Up")
~*Numpad8::RecorderKeys_RecordKey("Numpad8", "Down")
~*Numpad8 Up::RecorderKeys_RecordKey("Numpad8", "Up")
~*Numpad9::RecorderKeys_RecordKey("Numpad9", "Down")
~*Numpad9 Up::RecorderKeys_RecordKey("Numpad9", "Up")
~*NumpadDot::RecorderKeys_RecordKey("NumpadDot", "Down")
~*NumpadDot Up::RecorderKeys_RecordKey("NumpadDot", "Up")
~*NumpadDiv::RecorderKeys_RecordKey("NumpadDiv", "Down")
~*NumpadDiv Up::RecorderKeys_RecordKey("NumpadDiv", "Up")
~*NumpadMult::RecorderKeys_RecordKey("NumpadMult", "Down")
~*NumpadMult Up::RecorderKeys_RecordKey("NumpadMult", "Up")
~*NumpadAdd::RecorderKeys_RecordKey("NumpadAdd", "Down")
~*NumpadAdd Up::RecorderKeys_RecordKey("NumpadAdd", "Up")
~*NumpadSub::RecorderKeys_RecordKey("NumpadSub", "Down")
~*NumpadSub Up::RecorderKeys_RecordKey("NumpadSub", "Up")
~*NumpadEnter::RecorderKeys_RecordKey("NumpadEnter", "Down")
~*NumpadEnter Up::RecorderKeys_RecordKey("NumpadEnter", "Up")

~*F1::RecorderKeys_RecordKey("F1", "Down")
~*F1 Up::RecorderKeys_RecordKey("F1", "Up")
~*F2::RecorderKeys_RecordKey("F2", "Down")
~*F2 Up::RecorderKeys_RecordKey("F2", "Up")
~*F3::RecorderKeys_RecordKey("F3", "Down")
~*F3 Up::RecorderKeys_RecordKey("F3", "Up")
~*F4::RecorderKeys_RecordKey("F4", "Down")
~*F4 Up::RecorderKeys_RecordKey("F4", "Up")
~*F7::RecorderKeys_RecordKey("F7", "Down")
~*F7 Up::RecorderKeys_RecordKey("F7", "Up")
~*F8::RecorderKeys_RecordKey("F8", "Down")
~*F8 Up::RecorderKeys_RecordKey("F8", "Up")
~*F9::RecorderKeys_RecordKey("F9", "Down")
~*F9 Up::RecorderKeys_RecordKey("F9", "Up")
~*F10::RecorderKeys_RecordKey("F10", "Down")
~*F10 Up::RecorderKeys_RecordKey("F10", "Up")
~*F11::RecorderKeys_RecordKey("F11", "Down")
~*F11 Up::RecorderKeys_RecordKey("F11", "Up")
~*F12::RecorderKeys_RecordKey("F12", "Down")
~*F12 Up::RecorderKeys_RecordKey("F12", "Up")
#HotIf

RecorderKeysActive() {
    global recorderActive, recorderKbMouseEnabled
    return recorderActive && recorderKbMouseEnabled
}

RecorderKeys_RecordKey(keyName, state) {
    RecorderAddEvent("key", keyName, state)
}

RecorderKeys_RecordMouseButton(buttonName, state) {
    RecorderAddEvent("mousebtn", buttonName, state)
}
