// <auto-generated>
// This file is auto-generated by the Windows Forms designer.
// Manual edits may be overwritten. Edit MainForm.cs for custom logic.
// </auto-generated>
using MacrosApp.Controls;

namespace MacrosApp;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null;

    // Status bar
    private Panel statusPanel = null!;
    private Label statusLabel = null!;

    // Macro type buttons
    private Panel buttonPanel = null!;
    private Button btnSlashMacro = null!;
    private Button btnAutoclicker = null!;
    private Button btnTurboHold = null!;
    private Button btnPureHold = null!;
    private Button btnRecorder = null!;

    // Slot list
    private Panel slotPanel = null!;
    private Label slotHeaderLabel = null!;
    private SlotListControl slotList = null!;

    // Settings panel
    private Panel settingsPanel = null!;
    private Label settingsHeaderLabel = null!;
    private Label lblInterval = null!;
    private NumericUpDown nudInterval = null!;
    private Label lblSendMode = null!;
    private ComboBox cmbSendMode = null!;
    private Label lblLoopCount = null!;
    private NumericUpDown nudLoopCount = null!;

    // Controller panel
    private Panel controllerPanel = null!;
    private Label controllerHeaderLabel = null!;
    private ControllerStatePanel controllerState = null!;

    // Bottom status strip
    private StatusStrip statusStrip = null!;
    private ToolStripStatusLabel engineStatusLabel = null!;
    private ToolStripStatusLabel profileStatusLabel = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
            _hotkeyManager?.Dispose();
            controllerState?.StopRefresh();
        }
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    private void InitializeComponent()
    {
        this.components = new System.ComponentModel.Container();

        // --- Colors ---
        var bgDark = Color.FromArgb(25, 25, 25);
        var bgPanel = Color.FromArgb(32, 32, 32);
        var bgControl = Color.FromArgb(42, 42, 42);
        var fgMain = Color.FromArgb(220, 220, 220);
        var fgDim = Color.FromArgb(150, 150, 150);
        var accent = Color.FromArgb(0, 120, 215);
        var btnBg = Color.FromArgb(50, 50, 50);
        var btnHover = Color.FromArgb(60, 70, 85);

        // --- Form ---
        this.SuspendLayout();
        this.AutoScaleMode = AutoScaleMode.Dpi;
        this.ClientSize = new Size(520, 700);
        this.MinimumSize = new Size(480, 600);
        this.Text = "Macros";
        this.BackColor = bgDark;
        this.ForeColor = fgMain;
        this.Font = new Font("Segoe UI", 9.5f);
        this.StartPosition = FormStartPosition.CenterScreen;
        this.FormBorderStyle = FormBorderStyle.Sizable;
        this.Icon = null;

        // ============================================================
        // STATUS PANEL (top bar)
        // ============================================================
        statusPanel = new Panel
        {
            Dock = DockStyle.Top,
            Height = 38,
            BackColor = Color.FromArgb(20, 20, 20),
            Padding = new Padding(12, 0, 12, 0)
        };

        statusLabel = new Label
        {
            Text = "Idle",
            Dock = DockStyle.Fill,
            ForeColor = Color.FromArgb(100, 200, 100),
            Font = new Font("Segoe UI", 12f, FontStyle.Bold),
            TextAlign = ContentAlignment.MiddleLeft
        };
        statusPanel.Controls.Add(statusLabel);

        // ============================================================
        // MACRO TYPE BUTTONS
        // ============================================================
        buttonPanel = new Panel
        {
            Dock = DockStyle.Top,
            Height = 60,
            Padding = new Padding(8, 8, 8, 4),
            BackColor = bgDark
        };

        var buttonLayout = new TableLayoutPanel
        {
            Dock = DockStyle.Fill,
            ColumnCount = 5,
            RowCount = 1,
            BackColor = bgDark
        };
        buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20));
        buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20));
        buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20));
        buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20));
        buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20));

        btnSlashMacro = CreateMacroButton("/ Macro\nF1", btnBg, fgMain);
        btnAutoclicker = CreateMacroButton("Autoclicker\nF2", btnBg, fgMain);
        btnTurboHold = CreateMacroButton("Turbo Hold\nF3", btnBg, fgMain);
        btnPureHold = CreateMacroButton("Pure Hold\nF4", btnBg, fgMain);
        btnRecorder = CreateMacroButton("Recorder\nF5", btnBg, fgMain);

        buttonLayout.Controls.Add(btnSlashMacro, 0, 0);
        buttonLayout.Controls.Add(btnAutoclicker, 1, 0);
        buttonLayout.Controls.Add(btnTurboHold, 2, 0);
        buttonLayout.Controls.Add(btnPureHold, 3, 0);
        buttonLayout.Controls.Add(btnRecorder, 4, 0);

        buttonPanel.Controls.Add(buttonLayout);

        // ============================================================
        // SLOT LIST PANEL
        // ============================================================
        slotPanel = new Panel
        {
            Dock = DockStyle.Fill,
            Padding = new Padding(8, 4, 8, 4),
            BackColor = bgDark
        };

        slotHeaderLabel = new Label
        {
            Text = "Saved Recordings",
            Dock = DockStyle.Top,
            Height = 22,
            ForeColor = fgDim,
            Font = new Font("Segoe UI", 8.5f, FontStyle.Bold),
            Padding = new Padding(4, 2, 0, 0)
        };

        slotList = new SlotListControl
        {
            Dock = DockStyle.Fill
        };

        slotPanel.Controls.Add(slotList);
        slotPanel.Controls.Add(slotHeaderLabel);

        // ============================================================
        // BOTTOM SECTION (settings + controller, side by side)
        // ============================================================
        var bottomSplit = new SplitContainer
        {
            Dock = DockStyle.Bottom,
            Height = 230,
            Orientation = Orientation.Vertical,
            BackColor = bgDark,
            SplitterWidth = 4,
            Panel1MinSize = 100,
            Panel2MinSize = 100
        };
        bottomSplit.SplitterDistance = 230;

        // --- Settings Panel (left) ---
        settingsPanel = new Panel
        {
            Dock = DockStyle.Fill,
            Padding = new Padding(8, 4, 4, 4),
            BackColor = bgDark
        };

        settingsHeaderLabel = new Label
        {
            Text = "Settings",
            Dock = DockStyle.Top,
            Height = 22,
            ForeColor = fgDim,
            Font = new Font("Segoe UI", 8.5f, FontStyle.Bold),
            Padding = new Padding(4, 2, 0, 0)
        };

        var settingsInner = new TableLayoutPanel
        {
            Dock = DockStyle.Top,
            Height = 110,
            ColumnCount = 2,
            RowCount = 3,
            BackColor = bgDark,
            Padding = new Padding(4, 4, 4, 4)
        };
        settingsInner.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110));
        settingsInner.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        settingsInner.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
        settingsInner.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
        settingsInner.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));

        lblInterval = new Label
        {
            Text = "Click interval:",
            ForeColor = fgMain,
            Dock = DockStyle.Fill,
            TextAlign = ContentAlignment.MiddleLeft
        };
        nudInterval = new NumericUpDown
        {
            Minimum = 1,
            Maximum = 60000,
            Value = 100,
            Increment = 10,
            Dock = DockStyle.Fill,
            BackColor = bgControl,
            ForeColor = fgMain,
            BorderStyle = BorderStyle.FixedSingle
        };
        nudInterval.Controls[0].BackColor = bgControl; // spin buttons

        lblSendMode = new Label
        {
            Text = "SendMode:",
            ForeColor = fgMain,
            Dock = DockStyle.Fill,
            TextAlign = ContentAlignment.MiddleLeft
        };
        cmbSendMode = new ComboBox
        {
            Dock = DockStyle.Fill,
            DropDownStyle = ComboBoxStyle.DropDownList,
            BackColor = bgControl,
            ForeColor = fgMain,
            FlatStyle = FlatStyle.Flat
        };
        cmbSendMode.Items.AddRange(new object[] { "Input", "Play", "Event" });
        cmbSendMode.SelectedIndex = 0;

        lblLoopCount = new Label
        {
            Text = "Loop count:",
            ForeColor = fgMain,
            Dock = DockStyle.Fill,
            TextAlign = ContentAlignment.MiddleLeft
        };
        nudLoopCount = new NumericUpDown
        {
            Minimum = 0,
            Maximum = 99999,
            Value = 0,
            Dock = DockStyle.Fill,
            BackColor = bgControl,
            ForeColor = fgMain,
            BorderStyle = BorderStyle.FixedSingle
        };
        nudLoopCount.Controls[0].BackColor = bgControl;

        settingsInner.Controls.Add(lblInterval, 0, 0);
        settingsInner.Controls.Add(nudInterval, 1, 0);
        settingsInner.Controls.Add(lblSendMode, 0, 1);
        settingsInner.Controls.Add(cmbSendMode, 1, 1);
        settingsInner.Controls.Add(lblLoopCount, 0, 2);
        settingsInner.Controls.Add(nudLoopCount, 1, 2);

        settingsPanel.Controls.Add(settingsInner);
        settingsPanel.Controls.Add(settingsHeaderLabel);

        // --- Controller Panel (right) ---
        controllerPanel = new Panel
        {
            Dock = DockStyle.Fill,
            Padding = new Padding(4, 4, 8, 4),
            BackColor = bgDark
        };

        controllerHeaderLabel = new Label
        {
            Text = "Controller",
            Dock = DockStyle.Top,
            Height = 22,
            ForeColor = fgDim,
            Font = new Font("Segoe UI", 8.5f, FontStyle.Bold),
            Padding = new Padding(4, 2, 0, 0)
        };

        controllerState = new ControllerStatePanel
        {
            Dock = DockStyle.Fill
        };

        controllerPanel.Controls.Add(controllerState);
        controllerPanel.Controls.Add(controllerHeaderLabel);

        bottomSplit.Panel1.Controls.Add(settingsPanel);
        bottomSplit.Panel2.Controls.Add(controllerPanel);

        // ============================================================
        // STATUS STRIP (very bottom)
        // ============================================================
        statusStrip = new StatusStrip
        {
            BackColor = Color.FromArgb(20, 20, 20),
            ForeColor = fgDim,
            SizingGrip = true
        };

        engineStatusLabel = new ToolStripStatusLabel
        {
            Text = "Engine: checking...",
            ForeColor = fgDim,
            Spring = true,
            TextAlign = ContentAlignment.MiddleLeft
        };

        profileStatusLabel = new ToolStripStatusLabel
        {
            Text = "Profile: Default",
            ForeColor = fgDim,
            TextAlign = ContentAlignment.MiddleRight
        };

        statusStrip.Items.AddRange(new ToolStripItem[] { engineStatusLabel, profileStatusLabel });

        // ============================================================
        // ADD CONTROLS TO FORM (order matters for Dock)
        // ============================================================
        this.Controls.Add(slotPanel);          // Fill (added first, fills remaining)
        this.Controls.Add(bottomSplit);        // Bottom
        this.Controls.Add(buttonPanel);        // Top (below status)
        this.Controls.Add(statusPanel);        // Top (very top)
        this.Controls.Add(statusStrip);        // Bottom strip

        this.ResumeLayout(false);
        this.PerformLayout();
    }

    private static Button CreateMacroButton(string text, Color bg, Color fg)
    {
        var btn = new Button
        {
            Text = text,
            Dock = DockStyle.Fill,
            FlatStyle = FlatStyle.Flat,
            BackColor = bg,
            ForeColor = fg,
            Font = new Font("Segoe UI", 8f),
            Margin = new Padding(2),
            Cursor = Cursors.Hand,
            TextAlign = ContentAlignment.MiddleCenter
        };
        btn.FlatAppearance.BorderColor = Color.FromArgb(70, 70, 70);
        btn.FlatAppearance.BorderSize = 1;
        btn.FlatAppearance.MouseOverBackColor = Color.FromArgb(60, 70, 85);
        btn.FlatAppearance.MouseDownBackColor = Color.FromArgb(40, 60, 100);
        return btn;
    }

    #endregion
}
